//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        public int CharacterID { get; set; }
        public Nullable<int> PlayerID { get; set; }
        public string Region { get; set; }
        public string Realm { get; set; }
        public string Name { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
