//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LichKingDBEntities : DbContext
    {
        public LichKingDBEntities()
            : base("name=LichKingDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Boost> Boost { get; set; }
        public virtual DbSet<Dungeon> Dungeon { get; set; }
        public virtual DbSet<Player> Player { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Run> Run { get; set; }
        public virtual DbSet<Transaction> Transaction { get; set; }
    }
}
