//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Run
    {
        public int RunID { get; set; }
        public int PlayerID { get; set; }
        public int BoostID { get; set; }
        public int RoleID { get; set; }
        public Nullable<long> Gold { get; set; }
    
        public virtual Boost Boost { get; set; }
        public virtual Player Player { get; set; }
        public virtual Role Role { get; set; }
    }
}
