//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionID { get; set; }
        public int Type { get; set; }
        public long Amount { get; set; }
        public System.DateTime DateTime { get; set; }
        public int PlayerID { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
